services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: aiAvatar
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
  whisper:
    build:
      context: ./services/whisper
    volumes:
      - ./services/whisper/model:/models
    ports:
      - 8082:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  googletts:
    build:
      context: ./services/google
    ports:
      - 8083:8080
  video:
    build:
      context: ./services/video
    ports:
      - 8085:8080
    volumes:
      - shared:/root/share
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    volumes:
      - shared:/usr/src/myapp/share
  keycloak:
    image: keycloak/keycloak:26.2.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/aiAvatar
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_IMPORT: all
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8084:8080"
    depends_on:
      - db
    entrypoint:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-port=8080"
      - "--http-enabled=true"
  keycloak-init-service:
    build:
      context: ./keyCloak
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
volumes:
  shared: