services:
  certbot-selfsigned:
    build:
      context: ./cert-generator
    volumes:
      - ./certs:/certs
    environment:
      - DOMAIN=app.fb1-ecommerce.hs-rw.de
    restart: "no"

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: aiAvatar

  adminer:
    image: adminer:latest

  whisper:
    build:
      context: ./services/whisper
    volumes:
      - ./services/whisper/model:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  coqui:
    build:
      context: ./services/xtts
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COQUI_TOS_AGREED=1
      - COQUI_NON_COMMERCIAL=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - profiles:/app/profiles
      - transfer:/app/transfer
      - ./services/coqui/model:/root/.local/share/tts

  backend:
    container_name: backend
    build: .
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    volumes:
      - transfer:/usr/src/myapp/share/transfer
      - profiles:/usr/src/myapp/share/profiles
      - references:/usr/src/myapp/references

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - frontend_dist:/dist/src/app/dist/frontend/browser


  reverse_proxy:
    image: nginx:latest
    ports:
      - "8080:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs



  keycloak:
    image: keycloak/keycloak:26.2.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/aiAvatar
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_IMPORT: all
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8084:8081"
    depends_on:
      - db
    entrypoint:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--https-port=8081"
      - "--https-certificate-file=/certs/cert.pem"
      - "--https-certificate-key-file=/certs/key.pem"
    volumes:
      - ./certs:/certs

  keycloak-init-service:
    build:
      context: ./keyCloak
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"

  wav2lip:
    build:
      context: services/wav2lip
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTHONUNBUFFERED=1
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE:de
      - LC_ALL=de_DE.UTF-8
    volumes:
      - profiles:/app/Wav2Lip/profiles
      - transfer:/app/Wav2Lip/transfer


volumes:
  transfer:
  profiles:
  references:
  frontend_dist:
