services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - shared:/usr/src/myapp/share

volumes:
  shared: