services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: aiAvatar
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
  whisper:
    build:
      context: ./services/whisper
    volumes:
      - ./services/whisper/model:/models
    ports:
      - 8082:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  coqui:
    build:
      context: ./services/coqui
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - COQUI_TOS_AGREED=1
      - COQUI_NON_COMMERCIAL=1
    ports:
      - "8083:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - profiles:/app/profiles
      - transfer:/app/transfer
      - ./services/coqui/model:/root/.local/share/tts
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    volumes:
      - transfer:/usr/src/myapp/share/transfer
      - profiles:/usr/src/myapp/share/profiles
      - references:/usr/src/myapp/references
  keycloak:
    image: keycloak/keycloak:26.2.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/aiAvatar
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_IMPORT: all
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8084:8080"
    depends_on:
      - db
    entrypoint:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-port=8080"
      - "--http-enabled=true"
  keycloak-init-service:
    build:
      context: ./keyCloak
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
  wav2lip:
    build:
      context: services/wav2lip
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTHONUNBUFFERED=1
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE:de
      - LC_ALL=de_DE.UTF-8
    volumes:
      - profiles:/app/Wav2Lip/profiles
      - transfer:/app/Wav2Lip/transfer
    ports:
      - "8085:8080"
volumes:
  transfer:
  profiles:
  references: